config/routes.rb
Rails.application.routes.draw do
     devise_for :users
  root to: 'homes#top'
  
  resources :users, only: [:index, :create, :edit, :show, :update] 
  resources :books, only: [:index, :new, :show, :create, :edit, :update, :destroy] 
  get "home/about" => "homes#about", as: "about"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
     validates :name, uniqueness: true, length: { in: 2..20 }
    validates :introduction, length: { maximum: 50 }
  has_one_attached :profile_image


  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  

  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @books = Book.all
    @book = Book.new
   @user = current_user

  end

  def create
      @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
   redirect_to book_path(@book.id)
    else
   @user = current_user
   @books = Book.all
      flash[:notice] = ""
    render :index
    end
  end

  def edit
     @book = Book.find(params[:id])
  end

  def update
     @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] =  "You have updated book successfully."
     redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_create = Book.new
    @user = @book.user
  end

  def destroy
  books = Book.find(params[:id])
  books.destroy
  redirect_to '/books'
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

def is_matching_login_user
     book = Book.find(params[:id])
     unless book.user.id == current_user.id
       redirect_to books_path
     end
end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
  def about
    
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :is_matching_login_user, only: [:edit]

  def index
    @book = Book.new 
    @users = User.all
    @user = current_user
  end
  
   def create
      @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You have created book successfully."
   redirect_to user_path(@user.id)
    else
      flash.now[:notice] = "投稿に失敗しました。"
       @user = current_user
       @book = Book.new 
    render :index
    end
   end
  
  def edit
    @user = User.find(params[:id])
  end

  def show
     @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end
  
  def update
   @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
     redirect_to user_path(@user.id)
    else
    render :edit
    end
  end
  
end
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

 def is_matching_login_user
     user = User.find(params[:id])
     unless user.id == current_user.id
       redirect_to user_path(current_user.id)
     end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>


<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Body</h4>
<%= f.text_area :body %>
<%= f.submit "Update Book" %>
<%= link_to 'Show', book_path(@book.id) %>
<%= link_to "Back", books_path  %>
<% end %>

app/views/books/index.html.erb
<div class="container"> 
<div class="row"> 
<div class="col-md-3">
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'users/index', user:@user, book:@book %>
</div>
<div class="col-md-8 offset-md-1">

<h2>Books</h2>

<table class="table">
  <thead>
    <tr>
      <th colspan="2">Title</th>
      <th class="col">Opinion</th>
    </tr>
  </thead>

<tbody>
<% @books.each do |book| %>
<tr>
  <td class="col " >
    <%= link_to user_path(book.user.id) do %>
   <%= image_tag book.user.get_profile_image %></td>
<% end %>

  <td class="col"><%= link_to book.title, book_path(book.id) %></td>
  <td class="col"><%= book.body %></td>
</tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container"> 
<div class="row"> 
<div class="col-md-3">
      
<% if @book.errors.any? %>
 <%= @book.errors.count %>errors prohibited this obj from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>      

<%= render 'users/index', user:@user, book:@book_create %>

</div>
<div class="col-md-8 offset-md-1">

<h1>Book detail</h1>

<div class="d-flex justify-content-around border-top">

      <div class="m-1 " ><%=link_to user_path(@user) do %>
          <%= image_tag @user.get_profile_image %>
          <% end %></div>
      <div class="m-1 " ><%= link_to @user.name, user_path(@user.id)%></div>
      <div class="m-1"><%= link_to @book.title, book_path(@book.id) %></div>
      <div class="m-1"><%= @book.body %></div>
      <% if @book.user == current_user %>
      <div class="m-1"><%= link_to 'Edit', edit_book_path(@book.id) %></div>
      <div class="m-1"></div><%= link_to 'Destroy', book_path(@book.id), method: :delete, "data-confirm" => "Are you sure?" %>
       <% end %>
       </div>
       </div>
       </div>
       </div>

app/views/homes/about.html.erb
<h1>Welcome to <i class="fa-solid fa-book"></i>Bookers!</h1>
<p>CopyRight Infratop.inc</p>

app/views/homes/top.html.erb
<div class="text-center">
<h1>welcome to <i class="fa-solid fa-book"></i>Bookers !!</h1>
<h4>In <i class="fa-solid fa-book"></i>Bookers,</h4>
<p>you can share and exchange your opinions , inpressions , and emotions</br>
about various books!
</p>
<div class="rounded"><%= link_to "Log in", new_user_session_path %></div>
<div class="rounded"><%= link_to "Sign up", new_user_registration_path %></div>

<footer>
  <p>CopyRight Infratop.inc</p>
</footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/d179d9da83.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "d-flex flex-column vh-50">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
              <a href ="/">Bookers</a>
           <ul class="navbar-nav ml-auto">
       <% if user_signed_in? %>
    
        <li class="nav-item">
          
           <%= link_to user_path(current_user) do %></il>
           <i class="fa-solid fa-house"></i>Home
           <% end %>
        <li class="nav-item"><a href ="/users"><i class="fa-solid fa-users"></i>Users</a></il>
         <li class="nav-item"><a href ="/books"><i class="fa-solid fa-book-open"></i>Books</a></il>
        <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete do%>
            <i class="fa-solid fa-right-from-bracket"></i>Log out
          <% end %>  
        </li>
      <% else %>
        <li class="nav-item"><a href ="/"><i class="fa-solid fa-house"></i>Home</a></il>
        <li class="nav-item"><%=link_to about_path do %>
        <i class="fa-solid fa-link"></i>About
        <% end %>
        </il>
        <li class="nav-item">
          <%= link_to new_user_registration_path do  %>
          <i class="fa-solid fa-user-plus"></i>Sign up
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path do %>
          <i class="fa-solid fa-right-to-bracket"></i>Log in
          <% end %>
        </li>
      </ul>
      <% end %>
      </div>
      </nav>
    </header>
     <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    <div>
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/_index.html.erb
<h2>User info</h2>
  <div>
    <div class="border-bottom m-4 " >
    <% if user.profile_image.attached? %>
    <%= image_tag user.get_profile_image, size: "200x200" %>
  <% else %>
    <%= image_tag 'no_image', size: "200x200" %>
  <% end %></div>
    <div class="border-bottom m-4 " >name<%= user.name %></div>
    <div class="m-4" >introduction<%= user.introduction %></div>
  </div>
<div class="d-flex justify-content-center border rounded p-2">
<%= link_to edit_user_path(user), class: "btn btn-secondary w-100" do %>
<i class="fas fa-user-cog"></i>
<% end %>
</div calss ="p-3">
<h2>New book</h2>
<%= form_with model: book, url: '/books',method: :post do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>

<h4>Option</h4>
<%= f.text_area :body %>

<%= f.submit "Create Book"  %>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h2>User info</h2>



<div="d-flex　justify-content-between">
 <%= form_with model: @user do |f| %>
<label for ="inputName">Name</label>
<%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
<label for="inputImage">ProfileImage</label>
<%= f.file_field :profile_image, placehorder: "プロフィール画像", accept: "image/*"  %>
<label for ="inputIntroduction">introduction</label>
<%= f.text_area :introduction, autofocus: true, id:"inputIntroduction"%>
<%= f.submit "Update User" %>
</div>
<% end %>

app/views/users/index.html.erb
<div class="container"> 
<div class="row"> 
<div class="col-md-3">

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'index', user:@user, book:@book %>
</div>
<div class="col-md-8 offset-md-1">
  
<h2>Books</h2>

<table class="table">
  <thead>
    <tr>
      <th class="col">Image</th>
      <th class="col">name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

<tbody>
<% @users.each do |user| %>
<tr>
  <td class="col" >
  <%= image_tag user.get_profile_image %></td>
  <td class="col"><%= user.name  %></td>
  <td class="col"><%= link_to "Show", user_path(user.id) %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container"> 
<div class="row"> 
<div class="col-md-3">

<% if @book.errors.any? %>
 <%= @book.errors.count %>errors prohibited this obj from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'index', user:@user, book:@book %>
</div>
<div class="col-md-8 offset-md-1">
  
<h2>Books</h2>

<table class="table">
  <thead>
    <tr>
      <th class="col text-cente">Title</th>
      <th class="col">Option</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
<% @books.each do |book| %>
      <tr>
       <td class="col" ><%=link_to user_path(book.user.id) do %>
         <%= image_tag book.user.get_profile_image %>
          <% end %>
           </td>
      <td class="col"><%= link_to book.title, book_path(book.id) %></td>
      <td class="col"><%= book.body %></td>
      </tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>